### ISSUE TITLE
.travis.yml missing quote

### ISSUE THREAD

**Issue by alexbabushkindev** [allnes/pp_2020_spring#63]
**[`.travis.yml`](https://github.com/allnes/pp_2020_spring/blob/master/.travis.yml) строчка 21, пропущены закрывающие кавычки:**

``` yml
env: MATRIX_EVAL="CC=gcc-8 &&  CXX=g++-8
```

**Comment by alexbabushkindev** [comment]
@allnes

**Comment by allnes** [comment]
> @allnes

@alexbabushkindev исправил.
